### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by 75lb** [75lb/command-line-args#6]
- [ ] factor out `getOptionValueSet`
- [ ] option to pass whole `multiple:true` array output to a function/constructor
- [x] usage
  - [x] customise column widths
- [ ] _discarded property for unclaimed values
- [ ] permit arbitrary, un-defined options, and group them
